version: '3.9'

services:
  database:
    #    build:
    #      context: .docker/mariadb
    #      dockerfile: Dockerfile
    image: yobasystems/alpine-mariadb:latest
    container_name: cryptoob_database
    env_file:
      - .env
    networks:
      - cryptoob
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/mysql

  app:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: cryptoob_app
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - cryptoob
    restart: unless-stopped
    volumes:
      - ./:/var/www/app

  http:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    container_name: cryptoob_http
    depends_on:
      - app
    env_file:
      - .env
    networks:
      - cryptoob
    ports:
      - ${WEB_PORT}:80
      #- 4433:443
    restart: unless-stopped
    volumes:
      - ./:/var/www/app

networks:
  cryptoob:
    name: cryptoob

volumes:
  database_data:
